### ISSUE TITLE
Stream times are not synchronized

### ISSUE THREAD

**Issue by Matthew910818** [xdf-modules/xdf-Matlab#18]
Hi, I have tried to plot the channel data through Matlab, but however, the event markers are all at time = 0. Also, I have tried some solutions in the previous issues but still don't work.
The data was EEG data from  Muse2 Headband and the events were from python (pylsl) as a marker stream.

This is the code:

```python
import serial
from pylsl import StreamInfo, StreamOutlet, local_clock

serial_port = 'COM4'
baud_rate = 9600
ser = serial.Serial(serial_port, baud_rate)

info = StreamInfo('MyMarkerStream', 'Markers', 1, 0, 'string', 'myuid34234')
outlet = StreamOutlet(info)

while True:
    try:
        line = ser.readline().decode('utf-8').strip()
        timestamp = local_clock()
        print(type([line]))
        outlet.push_sample([line], timestamp)
        print(f"Sent data: {line} hz at time: {timestamp}")
    except KeyboardInterrupt:
        print("Exiting...")
        ser.close()
        break
    except Exception as e:
        print(f"An error occurred: {e}")
```
(Edited by Chad to add code-formatting tags around the code)

**Comment by cboulay** [comment]
>  tried to plot the channel data through Matlab

In real time, or did you save the data to xdf with LabRecorder then import it and try to plot it?

Your Python code looks good. If you're using LabRecorder to store the xdf then I don't see how anything could go wrong there. I would look at your import-and-plot code.

**Comment by Matthew910818** [comment]
I saved the data as a xdf file and simply press the plot button on eeglab in Matlab.
This is how I plot the data through eeglab:
<img width="1440" alt="截圖 2023-11-26 下午1 08 01" src="https://github.com/xdf-modules/xdf-Matlab/assets/107916838/2786d091-2afb-4438-bc8d-102d8e1dfaa2">

**Comment by cboulay** [comment]
OK this is an EEGLAB question, likely for @arnodelorme .
Maybe open your issue here: https://github.com/xdf-modules/xdf-EEGLAB

**Comment by cboulay** [comment]
I actually think the true source of the problem will be the timestamps provided by your Muse2 source are using the wrong clock, but I can't help you out because I can't investigate with EEGLAB.

**Comment by Matthew910818** [comment]
Alright, thanks a lot!
