### ISSUE TITLE
Very slow loading

### ISSUE THREAD

**Issue by iotzov** [xdf-modules/xdf-Matlab#3]
Not sure what the performance other people have been getting looks like, but I have experienced very slow loading when using the `load_xdf()` function in MATLAB.

My files are ~5GB, 64 channels EEG @ 2048 Hz and an audio recording with 2 channels @ 44.1 kHz. Loading times for each file are ~1hr.

This issue occurs on Windows, Ubuntu, and CentOS using MATLAB 2014b and 2018b.

Is this expected behavior? How can I speed up loading?

**Comment by iotzov** [comment]
Solved the issue, `load_xdf_innerloop.c` was incorrectly compiled and the `.mex` file was not working properly.

**Comment by JuliusWelzel** [comment]
> Solved the issue, `load_xdf_innerloop.c` was incorrectly compiled and the `.mex` file was not working properly.

Hey Ivan, I ran in the same Issue. Could you please provide a little more detailed way of solving the problem? I already tried to use an older version of the same file, which did not work.
